[package]
name = "rrr-head"
version = "0.1.0"
authors = ["Zageron <hello@adambryant.ca>"]
description = "Macroquad interface for the RRR game."
homepage = "https://github.com/flashflashrevolution/rrr"
repository = "https://github.com/flashflashrevolution/rrr"
readme = "README.md"
keywords = ["game"]
categories = ["games"]
license = "AGPL-3.0"
edition = "2021"
publish = false
rust-version = "1.64.0"

[features]
default = ["develop", "web"]
web = ["wgpu/webgl"]
develop = [
    "console_log",
    "simple_logger",
    "log/max_level_info",
    "log/release_max_level_info",
    "rrr-core/develop",
]
release = [
    "console_log",
    "simple_logger",
    "log/release_max_level_off",
    "rrr-core/release",
    "web",
]

[dependencies]
anyhow = "1.0.61"
cfg-if = "1.0.0"
image = { version = "0.24.3", default-features = false, features = ["png"] }
inter-struct = "0.2.0"
lerp = "0.4"
log = { version = "0.4.17" }
pixels = { git = "https://github.com/JMS55/pixels.git", branch = "main" }
rrr-core = { path = "../core", default-features = false }
winit = "0.27.2"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simple_logger = { version = "2.2.0", optional = true }
futures = "0.3.23"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "0.2.0", features = ["color"], optional = true }
gloo = "0.8.0"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
wgpu = "0.13.1"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.59"
features = ["Window", "Document", "EventListener"]
