[package]
name = "head"
version = "0.0.1"
authors = ["Zageron <hello@adambryant.ca>"]
description = "Macroquad interface for the RRR game."
homepage = "https://github.com/flashflashrevolution/rrr"
repository = "https://github.com/flashflashrevolution/rrr"
readme = "README.md"
keywords = ["game"]
categories = ["games"]
license = "AGPL-3.0"
edition = "2021"
publish = false

[features]
default = ["debug"]
debug = [
    "dep:egui",
    "dep:egui_wgpu_backend",
    "dep:egui-winit",
    "log/release_max_level_warn",
]
release = ["log/max_level_off"]

[dependencies]
egui = { version = "0.17.0", optional = true }
egui_wgpu_backend = { version = "0.17.0", optional = true }
egui-winit = { version = "0.17.0", default-features = false, features = [
    "links",
], optional = true }
game-loop = { git = "https://github.com/parasyte/game-loop.git", branch = "forward-main-events-cleared", features = [
    "window",
] }
log = "0.4.16"
pixels = { git = "https://github.com/parasyte/pixels.git" }
rrr = { path = "../rrr" }
winit = "0.26.1"
winit_input_helper = "0.11.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
web-sys = "0.3.57"
wgpu = { version = "0.12.0", features = ["webgl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9.0"
pollster = "0.2.5"
wgpu = "0.12.0"
