[package]
name = "head"
version = "0.0.1"
authors = ["Zageron <hello@adambryant.ca>"]
description = "Macroquad interface for the RRR game."
homepage = "https://github.com/flashflashrevolution/rrr"
repository = "https://github.com/flashflashrevolution/rrr"
readme = "README.md"
keywords = ["game"]
categories = ["games"]
license = "AGPL-3.0"
edition = "2021"
publish = false

[features]
default = ["develop"]
develop = [
    "dep:egui",
    "dep:egui_wgpu_backend",
    "dep:egui-winit",
    "console_log",
    "simple_logger",
    "log/max_level_info",
    "log/release_max_level_info",
]
release = ["log/release_max_level_off"]

[dependencies]
anyhow = "1.0.56"
cfg-if = "1.0.0"
egui = { version = "0.17.0", optional = true }
egui_wgpu_backend = { version = "0.17.0", optional = true }
egui-winit = { version = "0.18.0", default-features = false, features = [
    "links",
], optional = true }
game-loop = { git = "https://github.com/parasyte/game-loop.git", branch = "forward-main-events-cleared", features = [
    "window",
] }
log = { version = "0.4.16" }
pixels = { git = "https://github.com/parasyte/pixels.git" }
rrr = { path = "../rrr" }
winit = "0.26.1"
winit_input_helper = "0.12.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simple_logger = { version = "2.1.0", optional = true }
pollster = "0.2.5"
wgpu = "0.12.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "0.2.0", features = ["color"], optional = true }
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
wgpu = { version = "0.12.0", features = ["webgl"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.57"
features = ["Window"]
