[package]
name = "rrr"
version = "0.0.0"
authors = ["Fission", "Zageron"]
description = """
Rust Rust Revolution as a library.
"""
documentation = "https://docs.rs/rrr"
homepage = "https://github.com/flashflashrevolution/rrr"
repository = "https://github.com/flashflashrevolution/rrr"
readme = "README.md"
keywords = ["game"]
categories = ["games"]
license = "AGPL-3.0"
edition = "2018"

[package.metadata.docs.rs]
features = ["serde1"]

[features]
default = ["serde1"]
serde1 = ["serde", "num-rational/serde"]

[dependencies]
num-rational = { version = "0.3.2", default_features = false, features = ["std"] }
serde = { version = "1.0.120", optional = true, features = ["derive"] }
