name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Dependabot auto-merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.1
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
