name: CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - "LICENCE"
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - "LICENCE"

env:
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt:
    name: Rustfmt check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1

      - name: Install rust stable
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Rustfmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 1
          lfs: true

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libegl1-mesa-dev xorg-dev libasound2-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          components: llvm-tools-preview

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v1.3.0
        if: ${{ !env.ACT }}

      - name: Build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --workspace

      - name: Test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --workspace

  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color

  clippy:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 1
          lfs: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          components: llvm-tools-preview, clippy

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v1.3.0
        if: ${{ !env.ACT }}

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libegl1-mesa-dev xorg-dev libasound2-dev

      - name: Clippy
        run: cargo clippy --workspace -- -D warnings

  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [rustfmt, test, actionlint, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 1
          lfs: true

      - name: Install rust stable
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          components: llvm-tools-preview

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v1.3.0
        if: ${{ !env.ACT }}

      - name: API docs
        uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --workspace --no-deps

      - name: Deploy API docs
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: api

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1.1.14
        with:
          mdbook-version: latest

      - name: Book
        run: mdbook build docs

      - name: Deploy book
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          destination_dir: book
