name: code-coverage

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - "LICENCE"
      - ".github/workflows/web-release.yml"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Zinstrument-coverage
  LLVM_PROFILE_FILE: your_name-%p-%m.profraw

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          lfs: true

      - name: Install Dependencies
        run: sudo apt-get install libasound2-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v2.1.0
        if: ${{ !env.ACT }}

      - name: Extract Test Data
        run: 7z x -t7z ${{ github.workspace }}/assets/test-data.7z -o${{ github.workspace }}/ -p'${{ secrets.TEST_DATA_ARCHIVE_PASSWORD }}' -aoa

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo +nightly llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
