name: code-coverage

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - "LICENCE"
      - ".github/workflows/web-release.yml"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Zinstrument-coverage
  LLVM_PROFILE_FILE: your_name-%p-%m.profraw

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          lfs: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v1.3.0
        if: ${{ !env.ACT }}

      - name: Generate coverage report
        uses: Swatinem/fucov@v1.0.0

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
          fail_ci_if_error: true
          verbose: true
