name: web

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - "LICENCE"
      - ".github/workflows/code-coverage.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 1
          lfs: true

      - name: ⚡ Cache
        uses: actions/cache@v3.0.2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-web-release-${{ hashFiles('**/Cargo.lock') }}-0

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          components: llvm-tools-preview

      - name: Build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --package rrr-render --target wasm32-unknown-unknown --out-dir web -Z unstable-options

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          cname: rrr.flashflashrevolution.com
          keep_files: true
