name: web

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - "LICENCE"
      - ".github/workflows/code-coverage.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          lfs: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: llvm-tools-preview

      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: "latest"

      - name: ⚡ Cache
        uses: Swatinem/rust-cache@v2.0.0
        if: ${{ !env.ACT }}

      - name: Extract Test Data
        run: 7z.exe x -t7z ${{ github.workspace }}/assets/test-data.7z -o${{ github.workspace }}/ -p'${{ secrets.TEST_DATA_ARCHIVE_PASSWORD }}' -aoa

      - name: Build
        uses: actions-rs/cargo@v1.0.3
        env:
          TEST_PREVIEW_HASH: ${{ secrets.TEST_PREVIEW_HASH }}
        with:
          command: build
          args: --release --package rrr-head --target wasm32-unknown-unknown --target-dir target

      - name: Generate the .wasm for web deploy.
        run: wasm-bindgen --no-typescript --out-name rrr --out-dir web/bin --target web target/wasm32-unknown-unknown/release/rrr-head.wasm

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          cname: rrr.flashflashrevolution.com
          keep_files: true
